# Generated by Django 5.2.1 on 2025-06-01 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Подразделение')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
            },
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='item',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='user',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='item',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='writeoff',
            name='item',
        ),
        migrations.RemoveField(
            model_name='writeoff',
            name='user',
        ),
        migrations.RemoveField(
            model_name='writeoff',
            name='warehouse',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Вид МТС', 'verbose_name_plural': 'Виды МТС'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name': 'Склад', 'verbose_name_plural': 'Склады'},
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.CharField(max_length=50, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='location',
            field=models.TextField(blank=True, verbose_name='Местоположение'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Склад'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.department', verbose_name='Подразделение'),
        ),
        migrations.CreateModel(
            name='ItemCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Серийный номер')),
                ('batch', models.CharField(blank=True, max_length=100, verbose_name='Партия')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Срок годности')),
                ('storage_conditions', models.CharField(blank=True, max_length=255, verbose_name='Условия хранения')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество')),
                ('date_received', models.DateField(blank=True, null=True, verbose_name='Дата поступления')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.department', verbose_name='Подразделение')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item', verbose_name='Вид МТС')),
                ('warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Карточка МТС',
                'verbose_name_plural': 'Карточки МТС',
            },
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата перемещения')),
                ('type', models.CharField(choices=[('receipt', 'Поступление'), ('move', 'Перемещение'), ('writeoff', 'Списание')], max_length=20, verbose_name='Тип операции')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('from_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='move_from_dep', to='inventory.department', verbose_name='Откуда (подразделение)')),
                ('from_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='move_from', to='inventory.warehouse', verbose_name='Откуда (склад)')),
                ('item_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.itemcard', verbose_name='Карточка МТС')),
                ('to_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='move_to_dep', to='inventory.department', verbose_name='Куда (подразделение)')),
                ('to_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='move_to', to='inventory.warehouse', verbose_name='Куда (склад)')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Движение МТС',
                'verbose_name_plural': 'Движения МТС',
            },
        ),
        migrations.DeleteModel(
            name='Move',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
        migrations.DeleteModel(
            name='Receipt',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.DeleteModel(
            name='WriteOff',
        ),
    ]
