# Generated by Django 5.2.1 on 2025-06-01 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_department_remove_receipt_item_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouse',
            old_name='location',
            new_name='address',
        ),
        migrations.CreateModel(
            name='InventorySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_started', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала')),
                ('date_finished', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания')),
                ('status', models.CharField(choices=[('open', 'Открыта'), ('closed', 'Закрыта')], default='open', max_length=20, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Инвентаризация',
                'verbose_name_plural': 'Инвентаризации',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Код ячейки (адрес)')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Адрес хранения',
                'verbose_name_plural': 'Адреса хранения',
                'unique_together': {('warehouse', 'code')},
            },
        ),
        migrations.CreateModel(
            name='InventoryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_fact', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Факт. количество')),
                ('quantity_system', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сист. количество')),
                ('difference', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Отклонение')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('item_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.itemcard', verbose_name='Карточка МТС')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventorysession', verbose_name='Инвентаризация')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.location', verbose_name='Адрес хранения')),
            ],
            options={
                'verbose_name': 'Результат инвентаризации',
                'verbose_name_plural': 'Результаты инвентаризаций',
            },
        ),
        migrations.AddField(
            model_name='itemcard',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.location', verbose_name='Адрес хранения'),
        ),
    ]
