# Generated by Django 5.2.1 on 2025-06-02 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventorysession_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('ТО', 'ТО'), ('ремонт', 'Ремонт'), ('поверка', 'Поверка')], max_length=50, verbose_name='Вид обслуживания')),
                ('interval_days', models.PositiveIntegerField(verbose_name='Интервал (дней)')),
                ('next_due_date', models.DateField(verbose_name='Следующая дата обслуживания')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('item_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.itemcard', verbose_name='Оборудование')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный сотрудник')),
            ],
            options={
                'verbose_name': 'График ТО/ремонта',
                'verbose_name_plural': 'Графики ТО/ремонта',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_performed', models.DateField(verbose_name='Дата выполнения')),
                ('result', models.CharField(max_length=255, verbose_name='Результат')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_maintenance', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.maintenanceschedule', verbose_name='График обслуживания')),
            ],
            options={
                'verbose_name': 'Журнал ТО/ремонта',
                'verbose_name_plural': 'Журнал ТО/ремонта',
                'ordering': ['-date_performed'],
            },
        ),
    ]
