# Generated by Django 5.2.1 on 2025-06-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_supplier_purchaserequest_purchaserequestitem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={},
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='contract_file',
            field=models.FileField(blank=True, null=True, upload_to='contracts/', verbose_name='Файл договора'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='contract_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Номер договора'),
        ),
    ]
