# Generated by Django 5.2.1 on 2025-06-02 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_purchaseorder_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'verbose_name': 'Заказ поставщику', 'verbose_name_plural': 'Заказы поставщикам'},
        ),
    ]
