# Generated by Django 5.2.1 on 2025-06-03 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_purchaseorder_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcard',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.purchaseorder', verbose_name='Заказ поставщику'),
        ),
    ]
