# Generated by Django 5.2.1 on 2025-06-03 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_itemcard_purchase_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissioningAct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_number', models.CharField(max_length=100, verbose_name='Номер акта')),
                ('act_file', models.FileField(upload_to='acts/', verbose_name='Скан акта')),
                ('date_commissioned', models.DateField(verbose_name='Дата ввода в эксплуатацию')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('item_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissioning_acts', to='inventory.itemcard', verbose_name='Карточка МТС')),
            ],
            options={
                'verbose_name': 'Акт ввода в эксплуатацию',
                'verbose_name_plural': 'Акты ввода в эксплуатацию',
            },
        ),
    ]
