# Generated by Django 5.2.1 on 2025-06-03 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_commissioningact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('commission', 'Ввод в эксплуатацию'), ('receipt', 'Поступление'), ('move', 'Перемещение'), ('writeoff', 'Списание'), ('maintenance', 'ТО/Ремонт')], max_length=30, verbose_name='Тип события')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата/время')),
                ('description', models.TextField(blank=True, verbose_name='Описание/детали')),
                ('related_file', models.FileField(blank=True, null=True, upload_to='item_events/', verbose_name='Документ/файл')),
                ('item_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_logs', to='inventory.itemcard', verbose_name='Карточка МТС')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Событие по МТС',
                'verbose_name_plural': 'События по МТС',
                'ordering': ['-date'],
            },
        ),
    ]
